export * from './setup.routes'
export * from './countries.routes'
export * from './user.routes'
export * from './product.routes'
export * from './order.routes'
export * from './merchants.routes'
export * from './orderItem.routes'
export * from './merchantAct.routes'